source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target "uptous" do
    pod 'Alamofire'
    pod 'RandomColorSwift'
    pod "RappleProgressHUD"
    pod "Dropper"
    pod 'LKPullToLoadMore'
    pod 'GoogleMaps'
end


DEFAULT_SWIFT_VERSION = '5'
POD_SWIFT_VERSION_MAP = {
  'Alamofire' => '5',
  'RappleProgressHUD' => '5'
}

post_install do |installer|
  installer.pods_project.targets.each do |target|
    swift_version = POD_SWIFT_VERSION_MAP[target.name] || DEFAULT_SWIFT_VERSION
    puts "Setting #{target.name} Swift version to #{swift_version}"
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = swift_version
    end
  end
end

